Added Developer Guide
syndesisio/syndesis-project pull request #150
Opened 2017-10-25 12:12 UTC by paoloantinori

2017-10-25 12:56 UTC, gashcrumb requested changes
Just a couple little things, other than that looks good!

2017-10-25 12:56 UTC, gashcrumb commented on DevelopersGuide.md
> +sh syndesis-install
Switch these two commands around, i.e. `syndesis-install` and then `minishift-setup.sh`

Technically we could even consider adding yarn targets for both scripts, like `yarn setup:minishift`

2017-10-25 12:56 UTC, gashcrumb commented on DevelopersGuide.md
> +# after you have built atalsmap-ui project with yarn
Actually no need to build atlasmap-ui at all, this occurs when you build the main syndesis project.

2017-10-25 13:56 UTC, paoloantinori commented
Done. Would benefit from a squash merge.

2017-10-25 15:12 UTC, kahboom commented
Cool! Thanks @paoloantinori

2017-10-26 08:31 UTC, rhuss commented
Thanks @paoloantinori for writing this done, very helpful.

I hope we can setup a comprehensive document (asciidoc) in syndesisio/syndesis which combines various aspects into a single document.

2017-10-26 08:31 UTC, rhuss approved these changes
🏑

2017-10-26 08:31 UTC, merged