chore(credentials): Update design proposal
syndesisio/syndesis-project pull request #60
Opened 2017-07-17 14:51 UTC by zregvart

Updates the design proposal by removing the technical details not needed or not realized, updates the REST endpoints and the example payloads.

2017-07-18 11:12 UTC, jimmidyson commented on proposals/003-credentials.md
> +A citizen user during the creation of new connection selects `conect to _Service_`, this leads the user to the 3rd party service requiring the users credential to authorize Syndesis access on the use
typo: `conect` -> `connect`

2017-07-18 11:13 UTC, jimmidyson commented on proposals/003-credentials.md
> +A citizen user during the creation of new connection selects `conect to _Service_`, this leads the user to the 3rd party service requiring the users credential to authorize Syndesis access on the use
btw authorize and authorise are both fine in the land of real English :stuck_out_tongue:

2017-07-18 11:14 UTC, jimmidyson requested changes
one typo, but otherwise LGTM

2017-07-18 12:12 UTC, rhuss commented on proposals/003-credentials.md
> +A citizen user during the creation of new connection selects `conect to _Service_`, this leads the user to the 3rd party service requiring the users credential to authorize Syndesis access on the use
nit: "connect to _Service_"

2017-07-19 06:48 UTC, rhuss commented
thanks !

2017-07-19 06:48 UTC, merged